-- ============================================================
-- OpalSwift Feature Flag System
-- Migration: 20260608003000_feature_flag_system.sql
-- Anchor: > 20260608002700 (cron_platform_config)
-- ============================================================

-- STEP 1 — ENUMs and tenant columns
CREATE TYPE tenant_plan AS ENUM ('essential', 'professional');
CREATE TYPE tenant_skin AS ENUM ('essential', 'professional');
-- essential skin = appointment/freelancer layout
-- professional skin = class-roster/family-billing layout
CREATE TYPE tenant_vertical AS ENUM ('photographer', 'beautician', 'dance-studio', 'generic');
CREATE TYPE subscription_status AS ENUM ('trialing', 'active', 'past_due', 'canceled', 'suspended');

ALTER TABLE tenants
  ADD COLUMN plan          tenant_plan         NOT NULL DEFAULT 'essential',
  ADD COLUMN skin          tenant_skin         NOT NULL DEFAULT 'essential',
  ADD COLUMN vertical      tenant_vertical     NOT NULL DEFAULT 'generic',
  ADD COLUMN trial_ends_at TIMESTAMPTZ,
  ADD COLUMN sub_status    subscription_status NOT NULL DEFAULT 'trialing';

CREATE INDEX idx_tenants_plan     ON tenants(plan);
CREATE INDEX idx_tenants_skin     ON tenants(skin);
CREATE INDEX idx_tenants_vertical ON tenants(vertical);
CREATE INDEX idx_tenants_status   ON tenants(sub_status);


-- STEP 2 — feature_definitions
CREATE TABLE feature_definitions (
  key              TEXT        PRIMARY KEY,
  description      TEXT        NOT NULL,
  tier_minimum     tenant_plan NOT NULL,
  skin_restriction tenant_skin,
  deprecated_at    TIMESTAMPTZ,
  successor_key    TEXT        REFERENCES feature_definitions(key),
  created_at       TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE feature_definitions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "feature_defs_public_read"   ON feature_definitions FOR SELECT USING (true);
CREATE POLICY "feature_defs_service_write" ON feature_definitions FOR ALL
  USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');


-- STEP 3 — tenant_feature_overrides
CREATE TABLE tenant_feature_overrides (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id   UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  feature_key TEXT        NOT NULL REFERENCES feature_definitions(key) ON DELETE CASCADE,
  enabled     BOOLEAN     NOT NULL,
  expires_at  TIMESTAMPTZ,
  granted_by  TEXT,
  notes       TEXT,
  created_at  TIMESTAMPTZ DEFAULT now(),
  UNIQUE (tenant_id, feature_key)
);

CREATE INDEX idx_tfo_tenant  ON tenant_feature_overrides(tenant_id);
CREATE INDEX idx_tfo_expires ON tenant_feature_overrides(expires_at) WHERE expires_at IS NOT NULL;

ALTER TABLE tenant_feature_overrides ENABLE ROW LEVEL SECURITY;
CREATE POLICY "overrides_tenant_read" ON tenant_feature_overrides FOR SELECT
  USING (tenant_id = get_my_tenant_id());
CREATE POLICY "overrides_service_write" ON tenant_feature_overrides FOR ALL
  USING (auth.role() = 'service_role') WITH CHECK (auth.role() = 'service_role');


-- STEP 4 — get_tenant_features() resolver
CREATE OR REPLACE FUNCTION get_tenant_features(p_tenant_id UUID)
RETURNS TEXT[]
LANGUAGE plpgsql STABLE SECURITY DEFINER
AS $$
DECLARE
  v_plan           tenant_plan;
  v_skin           tenant_skin;
  v_status         subscription_status;
  v_trial_ends_at  TIMESTAMPTZ;
  v_effective_plan tenant_plan;
BEGIN
  SELECT plan, skin, sub_status, trial_ends_at
  INTO v_plan, v_skin, v_status, v_trial_ends_at
  FROM tenants WHERE id = p_tenant_id;

  IF v_status = 'trialing' AND (v_trial_ends_at IS NULL OR v_trial_ends_at > now()) THEN
    v_effective_plan := 'professional';
  ELSIF v_status IN ('active', 'past_due') THEN
    v_effective_plan := v_plan;
  ELSE
    RETURN ARRAY[]::TEXT[];
  END IF;

  RETURN ARRAY(
    SELECT fd.key
    FROM feature_definitions fd
    LEFT JOIN tenant_feature_overrides tfo
      ON tfo.tenant_id = p_tenant_id AND tfo.feature_key = fd.key
     AND (tfo.expires_at IS NULL OR tfo.expires_at > now())
    WHERE fd.deprecated_at IS NULL
      AND (v_effective_plan = 'professional'
           OR (v_effective_plan = 'essential' AND fd.tier_minimum = 'essential'))
      AND (fd.skin_restriction IS NULL OR fd.skin_restriction = v_skin)
      AND (tfo.enabled IS NULL OR tfo.enabled = true)

    UNION

    SELECT tfo.feature_key
    FROM tenant_feature_overrides tfo
    JOIN feature_definitions fd ON fd.key = tfo.feature_key
    WHERE tfo.tenant_id = p_tenant_id AND tfo.enabled = true
      AND (tfo.expires_at IS NULL OR tfo.expires_at > now())
      AND fd.deprecated_at IS NULL
  );
END;
$$;


-- STEP 5 — Seed feature_definitions (60 keys)
INSERT INTO feature_definitions (key, description, tier_minimum, skin_restriction) VALUES
  ('platform:tenant.isolation',  'Multi-tenant architecture with tenant isolation',    'essential',    NULL),
  ('platform:auth.enabled',      'User authentication and authorization',              'essential',    NULL),
  ('platform:i18n.enabled',      'Internationalization support (Hebrew/English)',       'essential',    NULL),
  ('platform:settings.manage',   'Tenant-level configuration management',              'essential',    NULL),
  ('platform:trial.enabled',     '14-day trial period for new tenants',                'essential',    NULL),
  ('platform:signup.selfServe',  'Self-service tenant registration',                   'essential',    NULL),
  ('platform:admin.super',       'Super-admin dashboard access',                       'professional', NULL),
  ('platform:domains.custom',    'Custom domain support',                              'professional', NULL),
  ('platform:themes.customize',  'Visual theme customization',                         'professional', NULL),
  ('people:contacts.manage',     'CRUD operations for people/contacts',                'essential',    NULL),
  ('people:families.manage',     'Family and account relationship management',         'professional', 'professional'),
  ('people:waivers.collect',     'Digital waiver and consent collection',              'essential',    NULL),
  ('people:evidence.hmac',       'HMAC-based evidence for legal compliance',           'essential',    NULL),
  ('offerings:classes.manage',      'CRUD for classes, services, and programs',        'essential',    NULL),
  ('offerings:structure.configure', 'Level, term, and session configuration',          'professional', 'professional'),
  ('offerings:enrollment.wizard',   'Multi-step enrollment wizard (admin)',             'essential',    NULL),
  ('offerings:enrollment.guest',    'Guest enrollment without login',                  'essential',    NULL),
  ('offerings:booking.public',      'Public self-service booking pages',               'professional', NULL),
  -- Cal.com: skin_restriction = 'essential' so it auto-resolves for appointment-layout
  -- tenants. Professional tenants opt-in via a single tenant_feature_overrides row.
  ('scheduling:appointments.calcom', '1:1 appointment scheduling via Cal.com OAuth',  'essential',    'essential'),
  ('scheduling:atoms.platform',      'Cal.com Platform Atoms integration',            'professional', NULL),
  ('scheduling:penalties.capture',   'No-show and late cancellation fee capture',     'professional', NULL),
  ('scheduling:ai.assistant',        'AI-powered scheduling assistant',               'professional', NULL),
  ('billing:payments.grow',     'Grow (Meshulam) payment gateway',                    'essential',    NULL),
  ('billing:payments.stripe',   'Stripe payment gateway',                             'essential',    NULL),
  ('billing:payments.mock',     'Mock payment processor for testing',                 'essential',    NULL),
  ('billing:accounts.manage',   'Per-family billing account management',              'essential',    NULL),
  ('billing:refunds.process',   'Refund processing capabilities',                     'essential',    NULL),
  ('billing:recurring.enabled', 'Recurring billing (הוראת קבע)',                     'professional', 'professional'),
  ('billing:quotes.generate',   'Quote generation and deposit handling',              'essential',    NULL),
  ('billing:dunning.enabled',   'Failed payment handling and dunning',               'professional', 'professional'),
  -- C-11: essential tier + essential skin so photographer tenants can use gated delivery
  ('billing:delivery.gated',    'Payment-gated file and gallery delivery',            'essential',    'essential'),
  ('finance:health.monitor',    'Financial health monitoring dashboard',              'essential',    NULL),
  ('finance:vat.calculate',     'VAT calculation and compliance',                     'essential',    NULL),
  ('finance:expenses.basic',    'Simple expense logging',                             'essential',    NULL),
  ('finance:expenses.advanced', 'Advanced expense tracking with VAT recovery',        'professional', NULL),
  ('finance:export.csv',        'Accountant CSV export functionality',                'essential',    NULL),
  ('finance:documents.tax',     'Tax document generation and management',             'essential',    NULL),
  ('finance:references.grow',   'Grow payment reference per transaction',             'essential',    NULL),
  ('finance:reports.realtime',  'Real-time profit & loss dashboard',                 'professional', NULL),
  ('finance:reports.annual',    'Annual accountant report generation',               'professional', NULL),
  ('finance:threshold.radar',   'Threshold radar for עוסק פטור → מורשה',            'professional', NULL),
  ('finance:export.bkmv',       'BKMVDATA export for accounting systems',            'professional', NULL),
  ('comms:notifications.log',   'Notification logging and audit trail',              'essential',    NULL),
  ('comms:preferences.manage',  'Contact preference management',                     'essential',    NULL),
  ('comms:otp.email',           'Email OTP verification',                            'essential',    NULL),
  ('comms:otp.sms',             'SMS OTP verification',                              'essential',    NULL),
  ('comms:otp.whatsapp',        'WhatsApp OTP verification',                         'professional', NULL),
  ('comms:reminders.whatsapp',  'WhatsApp payment reminders',                        'professional', NULL),
  ('comms:documents.whatsapp',  'WhatsApp tax document delivery',                    'professional', NULL),
  ('comms:reminders.voice',     'Voice call reminders with Hebrew TTS',              'professional', NULL),
  ('comms:documents.email',     'Tax document email delivery',                       'essential',    NULL),
  ('ui:admin.panel',            'Administrative panel access',                       'essential',    NULL),
  ('ui:client.portal',          'Client and parent portal',                          'essential',    NULL),
  ('ui:documents.queue',        'Failed document queue admin interface',              'professional', NULL),
  ('ui:pdfs.branded',           'Branded PDF invoice generation',                    'professional', NULL),
  ('ui:downloads.selfServe',    'Client self-service document downloads',            'professional', NULL),
  ('ui:onboarding.checklist',   'Tenant onboarding checklist',                       'professional', NULL),
  ('ui:payments.enhanced',      'Enhanced Stripe+Grow UX polish',                    'professional', NULL),
  ('ui:content.ai',             'AI content generation tools',                       'professional', NULL),
  ('ui:theme.photographer',     'Photographer vertical theme',                       'essential',    NULL),
  ('ui:theme.beautician',       'Beautician vertical theme',                         'essential',    NULL),
  ('ui:theme.dance-studio',     'Dance studio vertical theme',                       'professional', 'professional'),
  ('media:gallery.gated',       'Payment-gated gallery delivery for photographers',  'professional', 'essential');


-- STEP 6 — Seed existing tenants
UPDATE tenants SET
  vertical  = CASE business_preset WHEN 'programs' THEN 'dance-studio'::tenant_vertical ELSE 'generic'::tenant_vertical END,
  plan      = CASE business_preset WHEN 'programs' THEN 'professional'::tenant_plan     ELSE 'essential'::tenant_plan     END,
  skin      = CASE business_preset WHEN 'programs' THEN 'professional'::tenant_skin     ELSE 'essential'::tenant_skin     END,
  sub_status    = 'active',
  trial_ends_at = NULL;

-- Belt-and-suspenders Cal.com grant for essential tenants during migration
INSERT INTO tenant_feature_overrides (tenant_id, feature_key, enabled, granted_by, notes)
SELECT t.id, 'scheduling:appointments.calcom', true, 'system', 'Migration seeding: essential skin auto-grant'
FROM tenants t WHERE t.plan = 'essential'
ON CONFLICT (tenant_id, feature_key) DO NOTHING;


-- STEP 7 — _v2 DB functions

CREATE OR REPLACE FUNCTION public.handle_new_user_v2()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_tenant_id UUID;
  v_subdomain TEXT;
  v_email     TEXT;
BEGIN
  v_email     := NEW.email;
  v_subdomain := split_part(v_email, '@', 2);
  v_subdomain := split_part(v_subdomain, '.', 1);
  SELECT id INTO v_tenant_id FROM tenants WHERE subdomain = v_subdomain LIMIT 1;
  INSERT INTO public.user_profiles (id, tenant_id, role, email, created_at, updated_at)
  VALUES (NEW.id, v_tenant_id, ARRAY['account_holder']::TEXT[], v_email, NOW(), NOW())
  ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION provision_tenant_v2(
  p_name TEXT, p_subdomain TEXT,
  p_plan               tenant_plan     DEFAULT 'essential',
  p_vertical           tenant_vertical DEFAULT 'generic',
  p_owner_email        TEXT            DEFAULT NULL,
  p_language_default   TEXT            DEFAULT 'he',
  p_country            TEXT            DEFAULT 'IL',
  p_currency           TEXT            DEFAULT 'ILS',
  p_vat_rate           NUMERIC         DEFAULT 0.18,
  p_prices_include_vat BOOLEAN         DEFAULT true,
  p_phone_region       TEXT            DEFAULT 'IL',
  p_from_email         TEXT            DEFAULT NULL,
  p_payment_provider   TEXT            DEFAULT 'grow',
  p_invoicing_provider TEXT            DEFAULT 'grow',
  p_primary_color      TEXT            DEFAULT '#6366F1',
  p_accent_color       TEXT            DEFAULT '#8B5CF6'
)
RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_tenant_id UUID;
  v_skin      tenant_skin;
BEGIN
  v_skin := CASE p_vertical WHEN 'dance-studio' THEN 'professional'::tenant_skin ELSE 'essential'::tenant_skin END;
  INSERT INTO tenants (name, subdomain, plan, skin, vertical, sub_status, trial_ends_at,
    language_default, country, currency, vat_rate, prices_include_vat,
    phone_region, from_email, payment_provider, invoicing_provider, primary_color, accent_color)
  VALUES (p_name, p_subdomain, p_plan, v_skin, p_vertical, 'trialing', NOW() + INTERVAL '14 days',
    p_language_default, p_country, p_currency, p_vat_rate, p_prices_include_vat,
    p_phone_region, p_from_email, p_payment_provider, p_invoicing_provider, p_primary_color, p_accent_color)
  RETURNING id INTO v_tenant_id;

  IF p_vertical = 'photographer' THEN
    INSERT INTO tenant_feature_overrides (tenant_id, feature_key, enabled, granted_by, notes)
    VALUES (v_tenant_id, 'media:gallery.gated', true, 'system', 'Photographer vertical default');
  END IF;

  INSERT INTO expense_categories (tenant_id, name, description, is_vat_eligible, sort_order)
  SELECT v_tenant_id, c.name, c.description, c.is_vat_eligible, c.sort_order
  FROM (VALUES
    ('שכירות סטודיו','Studio rent',true,1), ('שכר מורים','Teacher wages',false,2),
    ('ציוד','Equipment and supplies',true,3), ('שיווק','Marketing and advertising',true,4),
    ('תוכנה ומנויים','Software subscriptions',true,5), ('ביטוח','Insurance',true,6),
    ('חשמל ומים','Utilities',true,7), ('שירותים מקצועיים','Accountant, lawyer, consultant',true,8),
    ('אחר','Other',true,9)
  ) AS c(name, description, is_vat_eligible, sort_order)
  ON CONFLICT (tenant_id, name) DO NOTHING;

  RETURN v_tenant_id;
END;
$$;

CREATE OR REPLACE FUNCTION get_tenant_config_by_subdomain_v2(p_subdomain TEXT)
RETURNS TABLE (
  id UUID, name TEXT, subdomain TEXT, business_preset TEXT,
  plan tenant_plan, skin tenant_skin, vertical tenant_vertical,
  sub_status subscription_status, trial_ends_at TIMESTAMPTZ, enabled_features TEXT[]
)
LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
BEGIN
  RETURN QUERY
  SELECT t.id, t.name, t.subdomain, t.business_preset,
         t.plan, t.skin, t.vertical, t.sub_status, t.trial_ends_at,
         get_tenant_features(t.id) AS enabled_features
  FROM tenants t WHERE t.subdomain = p_subdomain;
END;
$$;


-- STEP 8 — Swap trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_v2();


-- ROLLBACK (emergency only — destructive):
/*
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
DROP FUNCTION IF EXISTS get_tenant_config_by_subdomain_v2(TEXT);
DROP FUNCTION IF EXISTS provision_tenant_v2(TEXT,TEXT,tenant_plan,tenant_vertical,TEXT,TEXT,TEXT,TEXT,NUMERIC,BOOLEAN,TEXT,TEXT,TEXT,TEXT,TEXT,TEXT);
DROP FUNCTION IF EXISTS handle_new_user_v2();
DROP FUNCTION IF EXISTS get_tenant_features(UUID);
DROP TABLE IF EXISTS tenant_feature_overrides;
DROP TABLE IF EXISTS feature_definitions;
ALTER TABLE tenants DROP COLUMN IF EXISTS plan, DROP COLUMN IF EXISTS skin,
  DROP COLUMN IF EXISTS vertical, DROP COLUMN IF EXISTS sub_status, DROP COLUMN IF EXISTS trial_ends_at;
DROP TYPE IF EXISTS subscription_status; DROP TYPE IF EXISTS tenant_vertical;
DROP TYPE IF EXISTS tenant_skin; DROP TYPE IF EXISTS tenant_plan;
*/
